name: CI Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Run Tests
        run: npm test

      # ✅ Jira Integration Step
      - name: Jira Integration
        if: ${{ always() }}
        uses: rohit-gohri/jira-ci-cd-integration@v0
        with:
          state: ${{ job.status }}
          jira_instance: JIRA_INSTANCE # Replace with your Jira subdomain
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}
